### ISSUE TITLE
Rendre le jeu responsive

### ISSUE THREAD

**Issue by romainPrignon** [peaks-lyon/flappy-peaks#14]
Observation : 
Pour le moment, le jeu semble fonctionner sur tout appareil en mode portrait.

Bug : 
Si on passe en mode paysage, le jeux ne se redimensionne pas.
Sur grand écran (desktop) le jeux se cale a gauche de l'écran.

Piste de solution : 
Il semblerait que si l'on change la résolution du jeux, les élements ne s'affiche plus correctement. Ils semblent avoir été calculé pour se placé suivant la résolution 640x960. 
Solution longue :  tout recalculer
Solution courte : fixer la résolution, centrer le jeux, mettre un background

**Comment by Erazihel** [comment]
J'ai pas mal avancé la dessus, il m'reste encore 2 ou 3 petits trucs à corriger et après j'commit :)

**Comment by romainPrignon** [comment]
Je pene qu'on est plutot bon la dessus

**Comment by Erazihel** [comment]
Faudrait juste penser à mettre une largeur maximale !
